name: dropdown_kit
description: "A complete dropdown kit with search, multi-select and three display modes"
version: 0.0.1
homepage: https://github.com/ashiqu-ali/dropdown_kit
repository: https://github.com/ashiqu-ali/dropdown_kit
issue_tracker: https://github.com/ashiqu-ali/dropdown_kit/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

topics:
  - dropdown        
  - select          
  - multi-select    
  - search          
  - form            
  - overlay         
  - bottom-sheet    
  - dialog          